# Generated by Django 5.1.6 on 2025-02-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reg_number',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
    ]
